[package]
name = "mcpar-land-site"
version = "0.1.0"
edition = "2021"

[dependencies]
highlight-pulldown = "0.2.2"
maud = "0.25.0"
pulldown-cmark = "0.9.3"
zip = "0.5.13"               # pinned on old version for compat with zip-extensions
zip-extensions = "0.6.1"
